server:
  port: 8081


spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.208.40:3306/my-pro-db
    username: root
    password: 1234
  #redis
  redis:
    database: 0
    password: 578519083
    host: 39.106.208.40
    port: 6379


#mybatis-plus:
#  #  config-location: classpath:mybatis-config.xml
#  mapper-locations: classpath:mapper/redis/*.xml
#  type-aliases-package: com.ltc.redis.entity
